website/models.py
from __init__ import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):

    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key=True)

    profile_image = db.Column(db.String(20), nullable = False, default = 'default.png')
    email = db.Column(db.String(150), unique = True, index = True)
    username = db.Column(db.String(64), unique = True, index = True)
    age = db.Column(db.Integer)
    password_hash = db.Column(db.String(128))

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)



    def check_password(self, password): 
        return check_password_hash(self.password_hash, password)
    
    
    def __repr__(self):
        return f"User {self.username}"
    

website/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from website.models import User


#DataRequired() means must be filled
#Email() checks for indicators of an email

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('UserName', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm')])
    pass_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

class UpdateUserForm(FlaskForm): 
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    picture = FileField('Change Profile Picture', validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

website/Spotify/main.py
from dotenv import load_dotenv
import os
import json
import base64
from requests import post
from requests import get

load_dotenv()

client_id = os.getenv("CLIENT_ID")
client_secret = os.getenv("CLIENT_SECRET")


def get_token():
    '''
    creates the authorization string
    takes in client ID and client secret
    outputs them concatenated and encoded in base64

    '''
    auth_string = client_id + ":" + client_secret
    auth_bytes = auth_string.encode("utf-8")
    auth_base64 = str(base64.b64encode(auth_bytes), "utf-8")

    url = "https://accounts.spotify.com/api/token"
    headers = {
    "Authorization": "Basic " + auth_base64, "Content-Type": "application/x-www-form-urlencoded"
    } #SPACES MATTER WTF I ADDED A SPACE AFTER "BASIC" AND EVERYTHING WORKED
    data = {"grant_type": "client_credentials"}
    result = post(url, headers=headers, data=data)
    json_result = json.loads(result.content)
    token = json_result["access_token"]
    return token

def get_auth_header(token): #header is used to send future requests to API
    return {"Authorization": "Bearer " + token}

def search_for_artist(token, artist_name): #allows to search for artists, get their ID, and find associated track
    url = "https://api.spotify.com/v1/search"
    headers = get_auth_header(token)
    query = f"?q={artist_name}&type=artist&limit=3"

    query_url = url + query
    result = get(query_url, headers=headers)
    json_result = json.loads(result.content)["artists"]["items"]
    if len(json_result) == 0:
        print("Artist does not exist")
        return None
    
    return json_result[0]
     
def get_artist_albums(token,artist_id):
    url = f"https://api.spotify.com/v1/artists/{artist_id}/albums"
    headers = get_auth_header(token)
    result = get(url, headers = headers)
    json_result = json.loads(result.content)
    if "items" in json_result:
        return json_result["items"]
    else:
        return None

def get_related_artists(token,artist_id):
    url = f"https://api.spotify.com/v1/artists/{artist_id}/related-artists"
    headers = get_auth_header(token)
    result = get(url, headers = headers)
    json_result = json.loads(result.content)
    if len(json_result) == 0:
        print("Artist does not exist")
        return None
    return json_result
    


token = get_token()
result = search_for_artist(token, "Sabrina Carpenter")
print(result["name"])
artist_id = result["id"]
albums = get_artist_albums(token, artist_id)
for i, album in enumerate(albums):
    print(f"{i + 1}. {album['name']}")

related_artists = get_related_artists(token,artist_id)

for j, artist in related_artists:
    print(artist['name'])






'''The access token is a string which contains the credentials and permissions to access a given 
resource (e.g artists, albums or tracks) or user's data (e.g your profile or your playlists).'''

website/__init__.py
import os
from flask import Flask, redirect, url_for, render_template, request, session, flash
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
import sys
print(sys.path)

app = Flask(__name__)

#database
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
#

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

 

@app.route('/')
def index():
    return render_template('index.html')


@app.route('/about')
def info():
    return render_template('info.html')
    
from error_pages.handlers import error_pages


app.register_blueprint(error_pages)


import models

website/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')


@core.route('about')
def info():
    return render_template('info.html')
    

website/templates/base.html
<!DOCTYPE html>

<html lang = "en" dir = "ltr">

  <head>
      <meta charset = "utf-8">
      <title></title>
      <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
      />
      <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous">

      <script   src="https://code.jquery.com/jquery-3.7.1.min.js"   integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="   crossorigin="anonymous"></script>
      

  </head>

  <body>
      <ul class = 'nav'>
          <li class = 'nav-link'>
              <a href = "{{url_for('core.index')}}" >Home</a>
          </li>

          <li class = 'nav-link'>
              <a href = "{{url_for('core.info')}}" >About</a>
          </li>

          <li class= 'nav-link'>
              <a href = "#" >Log Out</a>

          </li>

          <li class= 'nav-link'>
              <a href = "#" >Account</a>
          </li>

          <li class= 'nav-link'>
              <a href = "#" >Edit Profile</a>
          </li>

          <li class= 'nav-link'>
              <a href = "#" >Account</a>
          </li>

          <li class= 'nav-link'>
              <a href = "#" >Register</a>

          </li>

          <li class= 'nav-link'>
              <a href = "#" >Log in</a>
          </li>

      </ul>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{{url_for('core.index')}}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{{url_for('core.info')}}">About <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Log out</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  More
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      <style>
          .container {
          background-image: url('file:///Users/olivia/Harmony/app/static/headphones.jpg'); 
          background-size: cover;
          background-position: center;
          color: white; 
          padding: 100px; 
          }
      </style>
    {% block content %}
    {% endblock %}
  </body>
</html>

website/templates/index.html
{% extends 'base.html' %}
{% block content %}

<style>
    .container {
	background-image: url('https://images.pexels.com/photos/9654031/pexels-photo-9654031.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'); 
	background-size: cover;
	background-position: center;
	color: white; 
	padding: 100px; 
    }
</style>

	<div class="jumbotron">
	  <h1 class="display-4">Harmony</h1>
	  <p class="lead">Music taste says more than you think.</p>
	  <hr class="my-4">
	  <p>A revolutionary new way to form new, lasting connections - one song at a time.</p>
	  <a class=".container" href="#" role="button">Learn more</a>
	</div>


	{% endblock %}

website/templates/info.html
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">About</h1>
    <p class="lead">Do you find it easier to click with people that share your music preferences? Well, look no further. Harmony's got you covered.</p>
    <hr class="my-4">
    <p>Create a profile and link your Spotify account to get started.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Start now</a>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block content %}

    <h1>Sign In</h1>
    
    <form action="" method="post" novalidate>
        <form>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>

{% endblock %}